In [31]:
import pickle

In [32]:
import numpy as np

In [33]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embark = pickle.load(open('models/ohe_embark.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [34]:
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)
test_input


array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [35]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(-1, 1))
test_input_embark = ohe_embark.transform(test_input[:, -1].reshape(-1, 1))

/home/hamza/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [36]:
test_input_sex

array([[0., 1.]])

In [37]:
test_input_embark

array([[0., 0., 1.]])

In [38]:
test_input_age = test_input[:,2].reshape(1,1)

In [39]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embark),axis=1)

In [42]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [41]:
clf.predict(test_input_transformed)

array([0])