1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [2]:
np.__version__

'1.26.4'

In [3]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /home/hamza/anaconda3/include
    lib directory: /home/hamza/anaconda3/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /home/hamza/anaconda3/lib/pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140137493227056
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong,
      -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/hamza/anaconda3/include,
      -fdebug-prefix-map=/croot/numpy_and_numpy_base_1708638617955/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/home/hamza/anaconda3=/usr/local/src/conda-prefix, -DNDEBUG,
      -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/hamza/anaconda3/

3. Create a null vector of size 10

In [4]:
nullVector = np.zeros(10)
nullVector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

In [5]:
size = nullVector.nbytes
size

80

5. How to get the documentation of the numpy add function from the command line?

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

6. Create a null vector of size 10 but the fifth value which is 1

In [7]:
array = np.zeros(10)
array[4]=1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49

In [8]:
vectorRanging = np.arange(10,50)
vectorRanging

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last)

In [9]:
reverseVector = vectorRanging[::-1]
reverseVector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
non_zero = np.nonzero(array)
non_zero

(array([4]),)

11. Create a 3x3 identity matrix

In [12]:
identityMatrix = np.identity(3)
identityMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values

In [13]:
randomValues = np.random.rand(3,3,3)
randomValues

array([[[0.73463476, 0.13509191, 0.71327885],
        [0.28123049, 0.32353505, 0.76286994],
        [0.5695034 , 0.03934272, 0.46020202]],

       [[0.75692487, 0.35694934, 0.48028499],
        [0.84072639, 0.10066211, 0.39209721],
        [0.06727914, 0.7798411 , 0.11803272]],

       [[0.19217938, 0.66014632, 0.90147748],
        [0.86993141, 0.33691354, 0.7486746 ],
        [0.93578483, 0.69347528, 0.52864504]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
randomArray = np.random.rand(10,10)
minimum = np.min(randomArray)
maximum = np.max(randomArray)
print(f"min : {minimum}     max : {maximum}")

min : 0.031058173548536905     max : 0.9963798510761843


In [15]:
vector = np.random.rand(30)
mean = np.mean(vector)
mean

0.5203056820268586

15. Create a 2d array with 1 on the border and 0 inside

In [28]:
twoDArray = np.zeros((10,5),dtype="int")

twoDArray[0,:] = 1
twoDArray[-1,:] = 1
twoDArray[:,0]=1
twoDArray[:,-1] = 1

twoDArray

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

16. How to add a border (filled with 0's) around an existing array?

In [16]:
borderArray = np.arange(1,10).reshape(3,3)
borderArray = np.pad(borderArray, pad_width=1, mode='constant', constant_values=0)
borderArray

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

nan
False
False
nan
True
False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [17]:
value = np.array([1,2,3,4,5])
diagonal = np.diag(value,k=-1)
diagonal

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [16]:
value = np.array([1,2,3,4,5])
diagonal = np.diag(value,k=1)
diagonal

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

In [17]:
diagonal = np.diag(value,k=0)
diagonal

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
array = np.zeros((8,8),dtype='int')
array[1::2,::2] = 1
array[::2,1::2] = 1
array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [19]:
array = np.zeros((6,7,8),dtype='int')
array[1,5,3]=99
array

array([[[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, 99,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,

21. Create a checkerboard 8x8 matrix using the tile function 

In [20]:
array = np.array([[1,0],[0,1]])

checkerboard = np.tile(array,[4,4])
checkerboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

22. Normalize a 5x5 random matrix

In [21]:
array = np.random.rand(5,5)
minValue = np.min(array)
maxValue = np.max(array)
normalize = ((array - minValue)/(maxValue-minValue))
normalize

array([[0.17382088, 0.13513656, 0.72919305, 0.01471616, 0.35300515],
       [0.26805736, 0.79249847, 0.15533545, 0.32736836, 0.29187636],
       [0.44099832, 0.11143203, 0.91510111, 1.        , 0.59356071],
       [0.17753677, 0.59759645, 0.75852671, 0.92620063, 0.        ],
       [0.61414766, 0.48864029, 0.06078259, 0.71186334, 0.90162988]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [22]:
dataType = np.dtype([('R',np.uint8),('G',np.uint8),('B',np.uint8),('A',np.uint8)])
array = np.array([(255,200,2,5)],dtype=dataType)

In [23]:
array

array([(255, 200, 2, 5)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

24. Multiply a 5x3 matrix by a 3x2 matrix

In [24]:
matrix1 = np.random.randint(1,16,(5,3))
matrix2 = np.random.randint(16,22,(3,2))
print(matrix1)
print(matrix2)

[[15  1  9]
 [13  1  7]
 [12  3  4]
 [ 7 11  3]
 [ 7 13  2]]
[[17 18]
 [18 20]
 [18 16]]


In [25]:
np.dot(matrix1,matrix2)

array([[435, 434],
       [365, 366],
       [330, 340],
       [371, 394],
       [389, 418]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [26]:
array = np.arange(1,10)

mask = ((array >=3) & (array <=8))
array[mask] *=-1
array

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9])

26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10

27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ilegal

Z <- Z

Z < Z > Z


28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array(nan)
arra(0)
error

29. How to round away from zero a float array ?

we can do this by two function floor() and ceil() functions so we will use both by where() function 'condition funtion'

In [27]:
array = np.random.rand(1,8)
print(array)
array = np.where(array >=0 , np.ceil(array),np.floor(array))

array

[[0.50786032 0.16067967 0.379603   0.44048408 0.10256947 0.49068128
  0.24735156 0.09440095]]


array([[1., 1., 1., 1., 1., 1., 1., 1.]])

30. How to find common values between two arrays?

In [28]:
common_values = np.intersect1d(matrix1,matrix2)
common_values

array([], dtype=int64)

31. How to ignore all numpy warnings (not recommended)? 

In [30]:
import warnings
#warnings.fliterwarnings("ignore")

32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)
Faslse

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
today = np.datetime64('today','D')
today

numpy.datetime64('2024-11-15')

In [35]:
tomorrow  = today + np.timedelta64(1,'D')
tomorrow

numpy.datetime64('2024-11-16')

In [37]:
yestraday = today - np.timedelta64(1,'D')
yestraday

numpy.datetime64('2024-11-14')

34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [44]:
start = np.datetime64('2016-07-01')
end = np.datetime64('2016-08-01')

july = np.arange(start,end)
july

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [56]:
A = np.array([1.0,2.0,3.0,4.0])
B = np.array([3.0,4.0,5.0,6.0])

A*=-(1/2)

A +=B

A

array([2.5, 3. , 3.5, 4. ])

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [61]:
method1 = np.floor(array)
method2 = np.trunc(array)
method3 = array.astype(int)
method4 = np.floor_divide(array,1)

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [65]:
array = np.arange(5)
matrix = np.tile(array,(5,1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

38. Consider a generator function that generates 10 integers and use it to build an array

#fromiter   function important

In [69]:
def generates():
    for i in range(1,11):
        yield i
array = np.fromiter(generates(),dtype='int')

array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [74]:
array = np.linspace(0,1,12)
array = array[1:-1]
array

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [76]:
array = np.random.uniform(0,1,10)
array

array([0.14014531, 0.47514414, 0.59698621, 0.80683255, 0.83354946,
       0.07248874, 0.3508892 , 0.78820762, 0.29224513, 0.48640185])

40. Create a random vector of size 10 and sort it (★★☆)

In [79]:
array = np.random.rand(10)
array = np.sort(array)
array

array([0.14938747, 0.16452678, 0.37446974, 0.43504273, 0.44828175,
       0.49797091, 0.68473843, 0.72965356, 0.77422605, 0.96544   ])