In [1]:
#importing numpy

import numpy as np

In [12]:
# intilizing numpy

a = np.array([1,23,4],dtype='int16')

In [4]:
b = np.array([[1,2,3],[4,5,6]])

In [5]:
print(a)

[ 1 23  4]


In [6]:
#Get dimension

b.ndim

2

In [7]:
#Get shape

In [8]:
b.shape

(2, 3)

In [9]:
#Get Type

In [10]:
b.dtype

dtype('int64')

In [13]:
a.dtype

dtype('int16')

In [15]:
#Get size
a.itemsize

2

In [16]:
b.itemsize

8

In [17]:
#Get total size
a.nbytes


6

In [18]:
# Get a specific element [r,c]
b[1,2]

6

In [19]:
# Get a specific row [r,:]
b[1,:]


array([4, 5, 6])

In [22]:
#Get a specific column[:,c]
b[:,1]

array([2, 5])

In [25]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# All 1s matrix
np.ones((3,4,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [31]:
# any other number
np.full((2,1),99,dtype='int8')

array([[99],
       [99]], dtype=int8)

In [32]:
#Random decimal numbers

In [33]:
np.random.rand(4,2)

array([[0.09936618, 0.05702308],
       [0.86904982, 0.97500418],
       [0.03902265, 0.00150866],
       [0.35784966, 0.46624077]])

In [39]:
# Random integar value 
np.random.randint(0,7, size=(2,3))

array([[4, 6, 5],
       [3, 0, 3]])

In [42]:
#indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])