In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#Get dimension
a.ndim

1

In [6]:
# Get shape
a.shape


(3,)

In [7]:
#Get type
a.dtype

dtype('int64')

In [10]:
# Get size
a.itemsize


8

In [16]:
b = np.array([[1,34,5,6],[3,45,6,4]])
print(b)

[[ 1 34  5  6]
 [ 3 45  6  4]]


In [18]:
# Get a specific element in using [row,column]
b[1,0]

3

In [20]:
# Get a specific row
b[0,:]

array([ 1, 34,  5,  6])

In [21]:
# Get a specific column
b[:,0]

array([1, 3])

In [24]:
#changing value
b[0,0]=5
print(b)

[[ 5 34  5  6]
 [ 3 45  6  4]]


In [25]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# all 1s matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
# any other numbers
np.full((2,3),88)

array([[88, 88, 88],
       [88, 88, 88]])

In [29]:
# Random decimal numbers
np.random.rand(2,4)


array([[0.2993429 , 0.62322459, 0.69718686, 0.92595443],
       [0.05929192, 0.29118205, 0.32408884, 0.11108094]])

In [35]:
#random intiger numbers
np.random.randint(2,5,size=(3,3))

array([[3, 4, 4],
       [2, 4, 4],
       [3, 2, 4]])

In [36]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
c = np.array([1,2,3])
d = np.rep